=== abraae/tas-core-apis/schemas/deltaSetStatus.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "app": {
            "type": "string"
        },
        "elapsedTime": {
            "description": "elapsed time of the operation in milliseconds",
            "type": "integer"
        },
        "deltaApplyStart": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "deltaApplyStart"
                    ]
                }
            }
        },
        "tenantDownStart": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "tenantDownStart"
                    ]
                }
            }
        },
        "appDownRequest": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "app"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "appDownRequest"
                    ]
                },
                "app": {
                    "$ref": "#/definitions/app"
                }
            }
        },
        "appDownComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "app"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "appDownComplete"
                    ]
                },
                "app": {
                    "$ref": "#/definitions/app"
                }
            }
        },
        "tenantDownComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "elapsedTime"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "tenantDownComplete"
                    ]
                },
                "elapsedTime": {
                    "$ref": "#/definitions/elapsedTime"
                }
            }
        },
        "applyIndividualDeltasStart": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "applyIndividualDeltasStart"
                    ]
                }
            }
        },
        "appInstallComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "app"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "appInstallComplete"
                    ]
                },
                "app": {
                    "$ref": "#/definitions/app"
                }
            }
        },
        "appEditComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "app"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "appEditComplete"
                    ]
                },
                "app": {
                    "$ref": "#/definitions/app"
                }
            }
        },
        "appUnInstallComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "app"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "appUnInstallComplete"
                    ]
                },
                "app": {
                    "$ref": "#/definitions/app"
                }
            }
        },
        "applyIndividualDeltasComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "elapsedTime"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "applyIndividualDeltasComplete"
                    ]
                },
                "elapsedTime": {
                    "$ref": "#/definitions/elapsedTime"
                }
            }
        },
        "tenantUpStart": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "tenantUpStart"
                    ]
                }
            }
        },
        "appUpComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "app"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "appUpComplete"
                    ]
                },
                "app": {
                    "$ref": "#/definitions/app"
                }
            }
        },
        "tenantUpComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "elapsedTime"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "tenantUpComplete"
                    ]
                },
                "elapsedTime": {
                    "$ref": "#/definitions/elapsedTime"
                }
            }
        },
        "deltaApplyComplete": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "kind",
                "elapsedTime",
                "newIncarnation"
            ],
            "properties": {
                "kind": {
                    "enum": [
                        "deltaApplyComplete"
                    ]
                },
                "elapsedTime": {
                    "$ref": "#/definitions/elapsedTime"
                },
                "newIncarnation": {
                    "type": "integer"
                }
            }
        },
        "orderedEvent": {
            "type": "object",
            "properties": {
                "seq": {
                    "type": "integer"
                },
                "event": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/deltaApplyStart"
                        },
                        {
                            "$ref": "#/definitions/tenantDownStart"
                        },
                        {
                            "$ref": "#/definitions/appDownRequest"
                        },
                        {
                            "$ref": "#/definitions/appDownComplete"
                        },
                        {
                            "$ref": "#/definitions/tenantDownComplete"
                        },
                        {
                            "$ref": "#/definitions/applyIndividualDeltasStart"
                        },
                        {
                            "$ref": "#/definitions/appInstallComplete"
                        },
                        {
                            "$ref": "#/definitions/appEditComplete"
                        },
                        {
                            "$ref": "#/definitions/appUnInstallComplete"
                        },
                        {
                            "$ref": "#/definitions/applyIndividualDeltasComplete"
                        },
                        {
                            "$ref": "#/definitions/tenantUpStart"
                        },
                        {
                            "$ref": "#/definitions/appUpComplete"
                        },
                        {
                            "$ref": "#/definitions/tenantUpComplete"
                        },
                        {
                            "$ref": "#/definitions/deltaApplyComplete"
                        }
                    ]
                }
            }
        }
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
        "kind",
        "launchKey",
        "incarnationPrior",
        "events"
    ],
    "properties": {
        "kind": {
            "enum": [
                "deltaSetStatus"
            ]
        },
        "launchKey": {
            "type": "integer"
        },
        "applyStatus": {
            "enum": [
                "complete",
                "inProcess",
                "notLaunched"
            ]
        },
        "latestEvent": {
            "type": "integer"
        },
        "incarnationPrior": {
            "type": "integer"
        },
        "events": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/orderedEvent"
            }
        }
    }
}

=== abraae/tas-core-apis/examples/deltaSetStatus.json
{
  "kind": "deltaSetStatus",
  "launchKey": 563064573256483661,
  "applyStatus": "complete",
  "latestEvent": 23,
  "incarnationPrior": 145,
  "events": [
    {"seq": 0, "event": {"kind": "deltaApplyStart"}},
    {"seq": 1, "event": { "kind": "tenantDownStart"}},
    {"seq": 2, "event": { "kind": "appDownRequest", "app": "tas-zoom"}},
    {"seq": 3, "event": { "kind": "appDownRequest", "app": "hrlabs-fratly"}},
    {"seq": 4, "event": { "kind": "appDownComplete", "app": "tas-zoom"}},
    {"seq": 5, "event": { "kind": "appDownRequest", "app": "tas-uberapply"}},
    {"seq": 6, "event": { "kind": "appDownComplete", "app": "tas-uberapply"}},
    {"seq": 7, "event": { "kind": "appDownComplete", "app": "hrlabs-fratly"}},
    {"seq": 8, "event": { "kind": "appDownComplete", "app": "tas-dummyjobs"}},
    {"seq": 9, "event": { "kind": "tenantDownComplete", "elapsedTime": 2033}},
    {"seq": 10, "event": { "kind": "applyIndividualDeltasStart"}},
    {"seq": 11, "event": { "kind": "appInstallComplete", "app": "tas-tracker"}},
    {"seq": 12, "event": { "kind": "appInstallComplete", "app": "supersoft-refly"}},
    {"seq": 13, "event": { "kind": "appEditComplete", "app": "tas-zoom"}},
    {"seq": 14, "event": { "kind": "appUnInstallComplete", "app": "tas-dummyjobs"}},
    {"seq": 15, "event": { "kind": "applyIndividualDeltasComplete", "elapsedTime": 3122}},
    {"seq": 16, "event": { "kind": "tenantUpStart"}},
    {"seq": 17, "event": { "kind": "appUpComplete", "app": "tas-zoom"}},
    {"seq": 18, "event": { "kind": "appUpComplete", "app": "hrlabs-fratly"}},
    {"seq": 19, "event": { "kind": "appUpComplete", "app": "tas-uberapply"}},
    {"seq": 20, "event": { "kind": "appUpComplete", "app": "supersoft-refly"}},
    {"seq": 21, "event": { "kind": "appUpComplete", "app": "tas-tracker"}},
    {"seq": 22, "event": { "kind": "tenantUpComplete", "elapsedTime": 533}},
    {"seq": 23, "event": { "kind": "deltaApplyComplete", "elapsedTime": 9603, "newIncarnation": 146}}
  ]
}
