=== abraae/tas-core-apis/schemas/patchSetLauncher.json
{
	"$schema":"http://json-schema.org/draft-04/schema#",
	"type":"object",
	"additionalProperties":false,
	"description":"reference to http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html",
	"properties":{
		"aud": { "type": "string", "description": "probably should be set to the name of the storefront app that requested this launcher"},
		"prep":{ "$ref": "./patchSetPreparer.json" },
		"iat":{
			"type":"string",
			"description":"time the token was issued, as per the spec."
		},
		"exp":{
			"type":"string",
			"description":"time the token expires, as per the spec."
		}
	},
	"required":[
		"prep",
		"aud",
		"iat",
		"exp"
	]
}

=== abraae/tas-core-apis/examples/patchSetLauncher-installApp.json
{
    "aud": "tas-storefront",
    "prep": {
        "continuePage": "https://storefront.com/apps/zwango",
        "patchSet": [
            {
                "op": "test",
                "path": "status.incarnation",
                "value": 23
            },
            {
                "op": "add",
                "path": "installs",
                "value": {
                    "app": "hrsoft-zwango"
                }
            }
        ]
    },
    "iat": "some time",
    "exp": "some time"
}
